version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3030 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3030:3030
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306


